# Generated by Django 4.2.1 on 2023-06-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavara', '0002_usuario_alter_misproductos_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuario_obj',
        ),
        migrations.AlterField(
            model_name='misproductos',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
